// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"KMS_Minimap","status":false,"description":"[v0.1.2] Display minimap.","parameters":{"Map rect":"524, 32, 260, 200","Grid size":"10","Blink time":"180","Foreground color":"rgba(224, 224, 240, 0.6)","Background color":"rgba(0, 0, 160, 0.6)","Mask style":"0","Mask radius":"48"}},
{"name":"GameusQuestSystem","status":false,"description":"v1.0 - 一個簡單的，具有許多可自行設定選項的任務系統。","parameters":{"Auto Rewards":"true","---------------":"","---文字翻譯---":"","Hidden Reward Text":"??????","No Quests Text":"沒有任務","All Word":"全部","Completed Word":"已完成","Failed Word":"已失敗","In-Progress Word":"進行中","Steps Word":"階段","Rewards Word":"報酬","---顯示選項---":"","Reverse Layout":"false","Filter Position":"Top","Use Categories":"true","Show Empty Categories":"0","Show Quest Count":"true","Bullet Character":"-","Max Steps":"3","---圖片和圖示選項---":"","Use Icons":"true","Completed Image":"","Completed Image Opacity":"128","Failed Image":"","Failed Image Opacity":"128"}}
];
